/**
 * Public keys for license verification
 * These are safe to ship with the app.
 *
 * IMPORTANT: Replace PLACEHOLDER_PUBLIC_KEY with the real Ed25519 public key hex
 * generated by tools/license-generator/generate-keypair.ts before release.
 *
 * The kid (key ID) allows for key rotation in the future.
 */
export const PUBLIC_KEYS: Record<string, string> = {
  'links-ed25519-2026-01': '16b6f31fa7811985bd00d0ae15850e221721b10feac254ada7e6f5135e7abc6b',
};
