/**
 * Research Notifications Repository
 *
 * Manages novelty/contradiction alerts generated by the deep research agent.
 */

import { randomUUID } from 'node:crypto';
import { getDatabase } from '../db.js';
import type { ResearchNotification, CreateResearchNotificationInput } from '../types.js';

function toNotification(row: any): ResearchNotification {
  return {
    id: row.id,
    pot_id: row.pot_id,
    run_id: row.run_id,
    type: row.type,
    message: row.message,
    metadata: row.metadata_json ? JSON.parse(row.metadata_json) : {},
    read_at: row.read_at ?? null,
    created_at: row.created_at,
  };
}

/**
 * Create a research notification
 */
export async function createResearchNotification(
  input: CreateResearchNotificationInput
): Promise<ResearchNotification> {
  const db = getDatabase();
  const now = Date.now();
  const id = randomUUID();

  await db
    .insertInto('research_notifications')
    .values({
      id,
      pot_id: input.pot_id,
      run_id: input.run_id,
      type: input.type,
      message: input.message,
      metadata_json: JSON.stringify(input.metadata ?? {}),
      read_at: null,
      created_at: now,
    })
    .execute();

  const row = await db
    .selectFrom('research_notifications')
    .selectAll()
    .where('id', '=', id)
    .executeTakeFirstOrThrow();

  return toNotification(row);
}

/**
 * Check if a notification of a given type already exists for this run (dedup)
 */
export async function notificationExistsForRun(
  runId: string,
  type: ResearchNotification['type']
): Promise<boolean> {
  const db = getDatabase();
  const row = await db
    .selectFrom('research_notifications')
    .select('id')
    .where('run_id', '=', runId)
    .where('type', '=', type)
    .limit(1)
    .executeTakeFirst();

  return row !== undefined;
}

/**
 * List notifications for a pot
 */
export async function listResearchNotifications(
  potId: string,
  opts: { unread_only?: boolean; limit?: number } = {}
): Promise<ResearchNotification[]> {
  const db = getDatabase();
  const limit = opts.limit ?? 20;

  let q = db
    .selectFrom('research_notifications')
    .selectAll()
    .where('pot_id', '=', potId);

  if (opts.unread_only) {
    q = q.where('read_at', 'is', null);
  }

  const rows = await q.orderBy('created_at', 'desc').limit(limit).execute();
  return rows.map(toNotification);
}

/**
 * Mark a notification as read
 */
export async function markResearchNotificationRead(id: string): Promise<void> {
  const db = getDatabase();
  await db
    .updateTable('research_notifications')
    .set({ read_at: Date.now() })
    .where('id', '=', id)
    .execute();
}
