import fs from 'fs';
import path from 'path';
import type { Db } from '../../db/index.js';
import type { ForgeRunOrchestrator } from '../scout/run_context.js';
import { ForgePacksDao } from '../db/dao/forge_packs.js';
import { logger } from '../../logging/logger.js';

export interface ForgeExportOptions {
  outDir: string;
}

export interface ForgeExportResult {
  packs_exported: number;
  outDir: string;
}

export async function exportForgePacks(
  db: Db,
  orchestrator: ForgeRunOrchestrator,
  opts: ForgeExportOptions
): Promise<ForgeExportResult> {
  const packsDao = new ForgePacksDao(db);
  const packs = packsDao.getByRunId(orchestrator.run_id);

  const runOutDir = path.join(opts.outDir, `forge_run_${orchestrator.run_id}`);
  fs.mkdirSync(runOutDir, { recursive: true });

  const generatedAt = new Date().toISOString();
  
  // Index Markdown
  let indexMd = `# Forge Packs — Run \`${orchestrator.run_id}\`

**Generated:** ${generatedAt}

| # | Score | Repos |
|---|-------|-------|
`;

  for (let i = 0; i < packs.length; i++) {
    const p = packs[i];
    const repoIds = JSON.parse(p.repo_ids_json) as string[];
    const repoNames = repoIds.map(id => {
      const row = db.prepare('SELECT full_name FROM repos WHERE repo_id = ?').get(id) as { full_name: string };
      return row?.full_name ?? id;
    });

    indexMd += `| ${i + 1} | ${p.score.toFixed(2)} | ${repoNames.join(', ')} |
`;

    // Individual Pack Markdown
    let packMd = `# Forge Pack ${i + 1}

**Synergy Score:** ${(p.score * 100).toFixed(1)}%
**Run ID:** \`${orchestrator.run_id}\`

---

## Synergy Reasoning

${JSON.parse(p.reasons_json)}

---

## Included Repositories

`;
    for (const name of repoNames) {
      packMd += `- **[${name}](https://github.com/${name})**
`;
    }

    packMd += `
---

## Integration Plan

${p.merge_plan_md}

---

*Generated by RepoForge*
`;

    fs.writeFileSync(path.join(runOutDir, `PACK_${i + 1}.md`), packMd, 'utf-8');
    
    // JSON Export
    fs.writeFileSync(path.join(runOutDir, `PACK_${i + 1}.json`), JSON.stringify(p, null, 2), 'utf-8');
  }

  fs.writeFileSync(path.join(runOutDir, 'index.md'), indexMd, 'utf-8');

  logger.info(
    { run_id: orchestrator.run_id, module: 'forge.export' },
    `Exported ${packs.length} packs to ${runOutDir}`
  );

  return { packs_exported: packs.length, outDir: runOutDir };
}
