import fs from 'fs';
import path from 'path';
import type { Db } from '../db/index.js';
import type { RunOrchestrator } from '../scout/run_context.js';
import { STEP_NAMES } from '../scout/run_context.js';
import { BriefsDao } from '../db/dao/briefs.js';
import type { BriefRow } from '../db/dao/briefs.js';
import { logger } from '../logging/logger.js';

export interface ExportOptions {
  outDir: string;
  /** Number of top-scoring briefs to export as TOP_OPPORTUNITY_N.md files. Default: 3. */
  topOpportunities?: number;
}

export interface ExportResult {
  briefs_exported: number;
  outDir: string;
}

function renderIndexMd(briefs: BriefRow[], runId: string, generatedAt: string): string {
  const header = `# Collaboration Briefs — Run \`${runId}\`

**Generated:** ${generatedAt}

| # | Title | Score | Status |
|---|-------|-------|--------|
`;
  const rows = briefs
    .map((b, i) => {
      const brief = JSON.parse(b.brief_json) as { title?: string };
      const title = brief.title ?? 'Untitled';
      const link = `[${title}](briefs/${b.brief_id}.md)`;
      return `| ${i + 1} | ${link} | ${b.score.toFixed(4)} | ${b.status} |`;
    })
    .join('\n');

  return header + rows + '\n';
}

function renderTopBriefMd(brief: BriefRow, rank: number): string {
  const data = JSON.parse(brief.brief_json) as {
    title: string;
    concept: string;
    repos: Array<{ full_name: string; why_it_fits: string; integration_role: string }>;
  };

  return `# #${rank}: ${data.title}

**Score:** ${(brief.score * 100).toFixed(1)}%
**Rank:** Top opportunity #${rank}

---

## Collaboration Concept

${data.concept}

---

## Repos

${data.repos.map((r) => `- **[${r.full_name}](https://github.com/${r.full_name})** (${r.integration_role}): ${r.why_it_fits}`).join('\n')}

---

## Outreach Draft

${brief.outreach_md}

---

*Generated by Collaboration Scout — review before sending.*
`;
}

export async function exportMarkdown(
  db: Db,
  orchestrator: RunOrchestrator,
  opts: ExportOptions
): Promise<ExportResult> {
  const step = orchestrator.startStep(STEP_NAMES.EXPORT_MARKDOWN);

  const briefsDao = new BriefsDao(db);
  const briefs = briefsDao.listByRunId(orchestrator.run_id);

  const runOutDir = path.join(opts.outDir, `run_${orchestrator.run_id}`);
  const briefsDir = path.join(runOutDir, 'briefs');
  fs.mkdirSync(briefsDir, { recursive: true });

  const generatedAt = new Date().toISOString();
  const indexMd = renderIndexMd(briefs, orchestrator.run_id, generatedAt);
  fs.writeFileSync(path.join(runOutDir, 'index.md'), indexMd, 'utf-8');

  // Export top N briefs as separate ranked opportunity files (briefs already sorted by score DESC)
  const topN = opts.topOpportunities ?? 3;
  for (let rank = 1; rank <= Math.min(topN, briefs.length); rank++) {
    const brief = briefs[rank - 1]!;
    const topBriefMd = renderTopBriefMd(brief, rank);
    fs.writeFileSync(path.join(runOutDir, `TOP_OPPORTUNITY_${rank}.md`), topBriefMd, 'utf-8');
  }

  let briefs_exported = 0;
  for (const brief of briefs) {
    fs.writeFileSync(path.join(briefsDir, `${brief.brief_id}.md`), brief.brief_md, 'utf-8');
    fs.writeFileSync(
      path.join(briefsDir, `${brief.brief_id}_outreach.md`),
      brief.outreach_md,
      'utf-8'
    );
    briefs_exported++;
  }

  orchestrator.logAudit({
    event: 'export.markdown.completed',
    message: `Exported ${briefs_exported} briefs to ${runOutDir}`,
    scope: STEP_NAMES.EXPORT_MARKDOWN,
    data: { briefs_exported, outDir: runOutDir },
  });

  logger.info(
    { run_id: orchestrator.run_id, module: 'export.markdown' },
    `Exported ${briefs_exported} briefs to ${runOutDir}`
  );

  step.finish('success', { briefs_exported });
  return { briefs_exported, outDir: runOutDir };
}
