-- Migration 006: Phase 7 - Derived Artifacts (Tags, Entities, Summary)
-- Purpose: Store AI-generated artifacts separately from original entries with full provenance
-- Created: 2026-02-14

PRAGMA foreign_keys = ON;

-- Derived artifacts table
-- Stores tags, entities, and summaries generated by AI processing
-- Each artifact includes full provenance: model, prompt version, temperature, etc.
CREATE TABLE derived_artifacts (
  id TEXT PRIMARY KEY NOT NULL,
  pot_id TEXT NOT NULL REFERENCES pots(id) ON DELETE CASCADE,
  entry_id TEXT NOT NULL REFERENCES entries(id) ON DELETE CASCADE,

  -- Artifact metadata
  artifact_type TEXT NOT NULL CHECK(artifact_type IN ('tags', 'entities', 'summary')),
  schema_version INTEGER NOT NULL DEFAULT 1,

  -- Provenance (full reproducibility)
  model_id TEXT NOT NULL,
  prompt_id TEXT NOT NULL,
  prompt_version TEXT NOT NULL,
  temperature REAL NOT NULL,
  max_tokens INTEGER,
  created_at INTEGER NOT NULL,

  -- Payload (validated JSON)
  payload_json TEXT NOT NULL,
  evidence_json TEXT,

  -- Uniqueness constraint: allows deterministic reprocessing
  -- Same entry + type + prompt version = same artifact (upsert)
  UNIQUE(entry_id, artifact_type, prompt_id, prompt_version)
) STRICT;

-- Index for querying artifacts by entry and type
CREATE INDEX idx_artifacts_entry_type_created
  ON derived_artifacts(entry_id, artifact_type, created_at DESC);

-- Index for querying artifacts by pot and type (pot-level views)
CREATE INDEX idx_artifacts_pot_type_created
  ON derived_artifacts(pot_id, artifact_type, created_at DESC);

-- Index for querying all artifacts by type (analytics, reprocessing)
CREATE INDEX idx_artifacts_type_created
  ON derived_artifacts(artifact_type, created_at DESC);
