-- Migration 008: Phase 8 - Link Discovery (Connection Finding)
-- Creates tables for link candidates and discovered links between entries

PRAGMA foreign_keys = ON;

-- ============================================================================
-- Link Candidates Table
-- ============================================================================
-- Stores candidate pairs for potential relationships (pre-AI classification)
-- Generated by deterministic heuristics (shared entities, tags, keywords, etc.)

CREATE TABLE link_candidates (
  id TEXT PRIMARY KEY NOT NULL,
  pot_id TEXT NOT NULL REFERENCES pots(id) ON DELETE CASCADE,
  src_entry_id TEXT NOT NULL REFERENCES entries(id) ON DELETE CASCADE,
  dst_entry_id TEXT NOT NULL REFERENCES entries(id) ON DELETE CASCADE,
  reason TEXT NOT NULL, -- e.g., 'shared_entities', 'shared_tags', 'keyword_sim', 'time_proximity', 'source_match'
  score REAL NOT NULL, -- heuristic confidence score (0..1)
  status TEXT NOT NULL DEFAULT 'new', -- 'new' | 'processed' | 'skipped'
  created_at INTEGER NOT NULL
) STRICT;

-- Ensure unique candidate pairs per pot (normalized order: src <= dst)
-- This prevents generating duplicate candidates in either direction
CREATE UNIQUE INDEX idx_link_candidates_unique_pair ON link_candidates(
  pot_id,
  MIN(src_entry_id, dst_entry_id),
  MAX(src_entry_id, dst_entry_id)
);

-- Index for efficient candidate processing (fetch unprocessed, highest score first)
CREATE INDEX idx_link_candidates_status_score ON link_candidates(status, score DESC);

-- Index for pot-level queries
CREATE INDEX idx_link_candidates_pot ON link_candidates(pot_id, created_at DESC);


-- ============================================================================
-- Links Table
-- ============================================================================
-- Stores discovered relationships between entries with AI classification and evidence

CREATE TABLE links (
  id TEXT PRIMARY KEY NOT NULL,
  pot_id TEXT NOT NULL REFERENCES pots(id) ON DELETE CASCADE,
  src_entry_id TEXT NOT NULL REFERENCES entries(id) ON DELETE CASCADE,
  dst_entry_id TEXT NOT NULL REFERENCES entries(id) ON DELETE CASCADE,

  -- Relationship classification
  link_type TEXT NOT NULL, -- 'same_topic' | 'same_entity' | 'supports' | 'contradicts' | 'references' | 'sequence' | 'duplicate' | 'other'
  confidence REAL NOT NULL, -- AI confidence score (0..1)
  rationale TEXT NOT NULL, -- short explanation from AI

  -- Evidence (JSON array of excerpts with offsets and side)
  -- Schema: [{ side: 'src'|'dst', start: number, end: number, excerpt: string }]
  evidence_json TEXT NOT NULL,

  -- Provenance (AI model and prompt tracking)
  model_id TEXT NOT NULL,
  prompt_id TEXT NOT NULL,
  prompt_version TEXT NOT NULL,
  temperature REAL NOT NULL,
  created_at INTEGER NOT NULL
) STRICT;

-- Enforce uniqueness for undirected link types (same_topic, same_entity, duplicate)
-- These are stored with normalized order: src = MIN(entry_id), dst = MAX(entry_id)
-- Directed types (supports, contradicts, references, sequence) preserve direction
-- and have separate uniqueness per direction
CREATE UNIQUE INDEX idx_links_unique_undirected ON links(
  pot_id,
  link_type,
  MIN(src_entry_id, dst_entry_id),
  MAX(src_entry_id, dst_entry_id)
) WHERE link_type IN ('same_topic', 'same_entity', 'duplicate');

-- Uniqueness for directed links (direction matters)
CREATE UNIQUE INDEX idx_links_unique_directed ON links(
  pot_id,
  link_type,
  src_entry_id,
  dst_entry_id
) WHERE link_type IN ('supports', 'contradicts', 'references', 'sequence', 'other');

-- Query optimization indexes
CREATE INDEX idx_links_pot_type_conf ON links(pot_id, link_type, confidence DESC);
CREATE INDEX idx_links_src ON links(src_entry_id, confidence DESC);
CREATE INDEX idx_links_dst ON links(dst_entry_id, confidence DESC);
CREATE INDEX idx_links_created_at ON links(created_at DESC);
